AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Invalidate

Resources:
 InvalidateFunction:
  Type: AWS::Serverless::Function
  Properties:
   FunctionName: invalidate
   CodeUri: .
   Handler: invalidate
   Timeout: 10
   Runtime: go1.x
  Policies:
   - Version: '2012-10-17'
     Statement:
      - Effect: 'Allow'
        Action:
         - codepipeline:PutJobSuccessResult
         - codepipeline:PutJobFailureResult
        Resource: '*'
      - Effect: 'Allow'
        Action:
         - cloudfront:CreateInvalidation
        Resource: "*"
